### ISSUE TITLE
About SunMoon University

### ISSUE THREAD

**Issue by zhaoshenglong** [Behamah/Sunmoon-Talk#17]
Hello, I am a chinese student and I noticed that recently, some of your students followed me. However, it seems that your account is new created in this year. Are you doing some experiment? Or are you making a robot which auto follow others ? If it is private and can not tell me, please also notice me. Thanks :)

**Comment by Behamah** [comment]
this can be misleading...

In Sunmoon Univ.'s DEPARTMENT OF COMPUTER SCIENCE & ENGINEERING, recently started a project that is about Open Source. The project's one of the evaluation standard is how much get the followers in GitHub. So, If I do following someone first, then the people who I do following can follow me either. As a result, followers can be increased, and get more score at that project...

At that reason, recently Sunmoon Univ's students do following someone who are related in their's areas of Interest...

If you are discomfortable, then apologize instead

**Comment by zhaoshenglong** [comment]
No, it's ok. 
I just felt confused, since I didn't have any feature repo in my hub. I thought you were robots and auto follows others Now that you are not robots, it's really ok indeed. So, it won't discomfort me, and good luck to you all. Now I will start following other students in your school, I thought they were robots. Thanks for answering,:)
