### ISSUE TITLE
안녕하세요, 궁금한 점이 있어서 이슈로 남깁니다.

### ISSUE THREAD

**Issue by wphestiraid** [Behamah/Sunmoon-Talk#18]
안녕하세요. 최근에 선문대학생의 여러 학생분들이 갑자기 절 많이 팔로우 해주셨는데, 갑작스럽게 증가한(?) 팔로우에 이유가 궁금해서 이슈로 남깁니다. 불쾌하거나 그런 게 아니라 단지 궁금해서 여쭤보는 것 뿐이니 답변 주시면 감사하겠습니다! ㅎㅎ

**Comment by Behamah** [comment]
아 이게 선문대학교의 컴퓨터 공학부에서 오픈소스 기반으로 프로젝트 개발하는걸 하고있는데, 평가 조건중 하나가 팔로워 늘리기입니다...
그리하여 일단 팔로잉을 하면 팔로우를 할 확률이 높아지니까 이런식으로 관심있는 주제와 관련된 프로젝트의 사람들을 일단 팔로우를 하는거죠...

많이 불편했다면 대신 사과드립니다(...)

**Comment by wphestiraid** [comment]
아 그렇군요 ㅋㅋㅋ 궁금했는데, 답변 감사합니다!
